CREATE TABLE students (
  PIN VARCHAR(13) PRIMARY KEY,
  name VARCHAR(50),
  branch VARCHAR(5),
  curr_sem VARCHAR(5),
  active_backlogs INT DEFAULT 0
);


CREATE TABLE subjects (
  SUB_ID VARCHAR(13) PRIMARY KEY,
  NAME VARCHAR(30)
);


CREATE TABLE results (
  RES_ID INT AUTO_INCREMENT PRIMARY KEY,
  PIN VARCHAR(13),
  SUB_ID VARCHAR(6),
  sem VARCHAR(5),
  marks INT,
  period VARCHAR(20),
  remarks VARCHAR(10),
  mode VARCHAR(10),
  FOREIGN KEY (PIN) REFERENCES students(PIN) ON DELETE CASCADE,
  FOREIGN KEY (SUB_ID) REFERENCES subjects(SUB_ID) ON DELETE CASCADE
);

CREATE TABLE backlogs (
  BACKLOG_ID INT AUTO_INCREMENT PRIMARY KEY,
  PIN VARCHAR(20),
  SUB_ID VARCHAR(20),
  sem VARCHAR(20),
  marks INT,
  period VARCHAR(20),
  mode VARCHAR(10),
  status VARCHAR(20),
  FOREIGN KEY (PIN) REFERENCES students(PIN) ON DELETE CASCADE,
  FOREIGN KEY (SUB_ID) REFERENCES subjects(SUB_ID) ON DELETE CASCADE
);


